### PR TITLE
Python generator to better handle unusual sized textures

### PR DESCRIPTION
**Pull request by benjaminwinger**
Following up #18, I've written a python generator script to simplify the atlas generators somewhat.

It does the following (which is mentioned in the script's docstring):
- Resizes textures to the correct size relative to the atlas size.
- Detects the size of the atlas based on the median size of the input textures
  (after adjusting for the ratios). Currently the only other choice for texture sizes is manually specifying the atlas width as a command line argument, but that could be improved. I seem to recall that one of the atlas generators let you resize the atlas by setting a scaling factor, maybe that would also be a useful option.
- Allows the atlas width to be referenced in commands using expressions such as `{3*width/2}` 
  (only fractions and multiplication are supported). This is meant for the things like the `-extent` commands where the sizes aren't for a specific texture. `-resize` should be able to be done by adjusting the ratios.
- Defines dds compression for output dds files.
- Combines the commands into a single magick command, allowing the use of in-memory mpr labels instead of temporary files (See https://imagemagick.org/Usage/files/#mpr) (also speeds things up a bit).
- Creates parent directories for output files if they don't exist already.
- Removes temporary bmp files after atlas generation is complete.

There are some assumptions currently being made about the structures of the commands, which maybe should also be documented. They could be fixed, but I'm not sure if it's necessary and it would just make the code more complicated for little gain.
- Changes to outputs (dds compression and creating parent directories) only apply to the implicit output at the end of a command. If you use `-write` to output in the middle of a command it will not be recognized as an output.
- The only special output type recognized is `mpr:`. It will try to create a parent directory for other special outputs since it thinks they are filenames, which may not work as expected (should be fine as long as the name doesn't contain path separators).

I'll see about putting together a script to convert the rest of the atlas generators, as I think most of them are simple enough to be converted automatically, and the more complicated ones should just need minor adjustments (e.g. to `-extent` arguments). I'll still double-check that the atlases they generate are correct.

Closes #18

### CODE REVIEW

**Comment by revenorror** [comment]
Thanks for the helping out with this. Some thoughts I had about the atlas generator-
I think the best solution for scaling would be if the user could set a universal preference for vanilla res, 2x, or 4x resolution, then up/downscale any textures as appropriate. The very large atlases at 4x res can cause memory issues on some computers so an option for 4x res for everything except buildings/specified atlases to be 2x would be good too. In the future PA will cover armor, weapons etc so I would also like to reorganize the atlas handler into separate categories, and have options to run all atlases based on category, etc, in case you plan on rewriting the atlas handler and feel like adding some backend organization of everything. 
As for the dds compression, it's not as common but some textures do use dxt5 instead of dxt1. The raven rock roof atlas I think is the only one so far. You could probably assume dxt1 but then allow an override for dxt5. But I'll go ahead and merge these, sorry for taking a bit to get back to you

**Comment by benjaminwinger** [comment]
I've finally gotten back to this, and I figure that it would work better to store the vanilla resolutions in the template file instead of the ratios, that way it's easy to allow the user to specify a multiplier for the size, and it also works well with the atlas generators which produce multiple atlases. I wrote a script to convert them (which works for most of them, but some need adjustments) and I've gone through and verified about half of them so far. I should be able to get through the rest soon.

Using a bash or similar shell you could run something like `./atlasgen.py --multiplier 2 *.atlas` to use the multiplier for all of them (doesn't work in windows CMD due to a lack of , but I'll work on some sort of system for saving preferences for specific atlas generators which can also work with the interactive atlas handler script. 

Since the script already can detect a multiplier that matches the textures being used, maybe it could prompt for a multiplier with the default option being the one that was detected. That could work well if you're just running a single generator, but it could be cumbersome if you're running all of them at once.

There could alternatively, or even additionally, be some sort of setting file to store the user's preferred size multipliers, with a way to set the multiplier globally, for each category and for each individual atlas. 

> As for the dds compression, it's not as common but some textures do use dxt5 instead of dxt1. The raven rock roof atlas I think is the only one so far.

I guess I hadn't seen that one. I'll change it so that the default can be overridden.

**Comment by revenorror** [comment]
That all sounds good. I think some way to store a resolution preference would be good, although the only thing i'm thinking is it seems a bit of a waste to have a settings file for just one setting. Maybe you could add the resolution prompt into the atlas handler instead of the individual bat files, or add an options menu into it? since i think most users should probably be using the handler instead of running the bats directly.

**Comment by benjaminwinger** [comment]
Okay. A prompt in the handler that sets the multiplier for everything that's being run at once would be easy enough. I'm not sure that I understand the benefit of an options menu if there's no settings file, unless the idea is to use a default value instead of always prompting and an options menu to override that, however I'm not sure that's any more convenient than having a default value in the prompt so that the user just has to hit enter to skip it. On the other hand I can imagine having it so that it prompts only the first time and stores it in a settings file for subsequent runs, with a choice in the selection menu to re-run that prompt and change the setting.

What I was also thinking was that the atlas handler could be merged into the python script, mostly so that the choices in the handler could be automatically generated by scanning for the atlas files (which could probably be done in the `.bat` script but I'm not that familiar with `.bat` scripting and I think it would be easier in python). The atlases could be categorized too by creating directories for each category.

**Comment by revenorror** [comment]
Yeah, the only benefit for an options menu would just be reconfiguring the resolution, unless we come up with other options to put in there. Maybe in 10 years ill move on to covering oblivion lol. Mostly I was just spitballing ideas, implement whatever in what way you think makes sense. 

> On the other hand I can imagine having it so that it prompts only the first time and stores it in a settings file for subsequent runs, with a choice in the selection menu to re-run that prompt and change the setting.
Yeah, something like this is what I had in mind.

Really, I think the only reason the original scripts were written as BAT files was just because that was a way to interface with Image Magick. If you'd like you could ditch them entirely and just rewrite everything in Python.

**Pull request merged**
